spring:
  datasource:
    url: jdbc:mysql://localhost:3306/1904_springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*.xml
server:
  port: 8804
  servlet:
    context-path: /
